[package]
name = "dt_renamer"
version = "0.1.0"
edition = "2021"

[features]
default = ["regex_match"]
regex_match = ["regex"]

[dependencies]
dt_walker = { version = "0.1.0", path = "../dt_walker" }
itertools = "0.11"
regex = { version = "1.0", optional = true }
